# Generated by Django 4.1.7 on 2023-03-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
